name: code-check
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'LIEF branch'
        default: master
        required: false
        type: string
      what:
        description: 'clang tidy action'
        default: latest
        required: false
        type: string
  push:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: liefproject/code-check
      env:
        LIEF_S3_KEY: ${{ secrets.LIEF_S3_KEY }}
        LIEF_S3_SECRET: ${{ secrets.LIEF_S3_SECRET }}
        GH_BRANCH: ${{ github.event.inputs.branch }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lief-project/code-check
          token: ${{ secrets.LIEF_CLONE_TOKEN }}
      - name: Print info
        run: |
          echo ${GH_BRANCH}
      - name: Running LIEF coverage
        run: ./lief-coverage --debug
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: liefproject/code-check
      env:
        LIEF_S3_KEY: ${{ secrets.LIEF_S3_KEY }}
        LIEF_S3_SECRET: ${{ secrets.LIEF_S3_SECRET }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lief-project/code-check
          token: ${{ secrets.LIEF_CLONE_TOKEN }}
      - name: Running LIEF coverage [workflow dispatch]
        if: "github.event.name == 'workflow_dispatch'"
        run: ./lief-tidy --branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.what }}
      - name: Running LIEF coverage [regular]
        if: "github.event.name != 'workflow_dispatch'"
        run: ./lief-tidy latest
